name: Update latest blog posts
permissions:
  contents: read
  pull-requests: write
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch and update blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/tahmidbintaslim,https://medium.com/feed/@tahmidbintaslimrafi"
          max_post_count: 5

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git checkout -b update-blog-posts
          git add README.md
          git commit -m "Update latest blog posts"

      - name: Push changes to a new branch
        run: |
          git push origin update-blog-posts

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: update-blog-posts
          title: Update latest blog posts
          body: |
            This pull request updates the README with the latest blog posts.
          labels: blog-updates
